
import json
from urllib.request import urlopen



"""
	Following header is necessary for requesting golemio api.
	code copied from https://golemioapi.docs.apiary.io/#reference/public-transport/vehicle-positions/get-all-vehicle-positions
	access token generated by https://api.golemio.cz/api-keys/auth/sign-in
"""

headers = {
	'Content-Type': 'application/json; charset=utf-8',
	'x-access-token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNpem1hcmZpbGlwQGdtYWlsLmNvbSIsImlkIjo3NiwibmFtZSI6bnVsbCwic3VybmFtZSI6bnVsbCwiaWF0IjoxNTcwNTQ2MTU2LCJleHAiOjExNTcwNTQ2MTU2LCJpc3MiOiJnb2xlbWlvIiwianRpIjoiMzAxYWNhNDUtNGRlNC00ZDRmLWI4NzAtMzQwMDQ5OTM1MzBhIn0.4rCELzCNY8XOSvjqQA7cKocPGJ8D2ezhXiWUkIRUNjg'
}


"""
	This function downloads file of given url request and returns decoded json object
"""
def downloadURL(request):
	webURL = urlopen(request)
	response_body = webURL.read()
	encoding = webURL.info().get_content_charset('utf-8')
	return json.loads(response_body.decode(encoding))


def sql_get_result(cursor, sql_query, params=()):
	cursor.execute(sql_query, params)
	return cursor.fetchall()


def sql_run_transaction(connection, cursor, sql_query, params=()):
	cursor.executemany(sql_query, params)
	connection.commit()


def sql_run_transaction_and_fetch(connection, cursor, sql_query, params=()):
	cursor.executemany(sql_query, params)
	connection.commit()
	return cursor.fetchall()