#!/usr/bin/env python3
from urllib.request import Request, urlopen
import json

from common_functions import downloadURL
from common_functions import URLs



json_veh_pos = downloadURL(URLs.vehicles_positions)

print(json_veh_pos)

# pole = [1,2,3, 4,5,6]
# print(min(pole))
