import argparse
from urllib.error import URLError
from urllib.request import Request, urlopen
import time
import json
import logging
import os
from pathlib import Path
from collections import deque


def downloadURL(request):
	webURL = urlopen(request)
	response_body = webURL.read()
	encoding = webURL.info().get_content_charset('utf-8')
	return json.loads(response_body.decode(encoding))


def transform_shape_json_file(old_json_data):
	new_json_data = {}
	new_json_data["type"] = "FeatureCollection"
	new_json_data["features"] = [None]
	new_json_data["features"][0] = {}
	new_json_data["features"][0]["type"] = "Feature"
	new_json_data["features"][0]["geometry"] = {}
	new_json_data["features"][0]["geometry"]["type"] = "LineString"
	new_json_data["features"][0]["geometry"]["properties"] = {}
	new_json_data["features"][0]["geometry"]["coordinates"] = []
	for feature in old_json_data["shapes"]:
		new_json_data["features"][0]["geometry"]["coordinates"].append(feature["geometry"]["coordinates"])
	return new_json_data

def is_old(coordinates):
	from datetime import datetime
	fmt = '%H:%M:%S'
	coordinates_time = coordinates[1]
	now = datetime.now().strftime(fmt)
	tdelta = datetime.strptime(now, fmt) - datetime.strptime(coordinates_time, fmt)
	seconds = tdelta.total_seconds()
	if seconds > 10*60:
		return True
	return False

"""
	Following header is necessary for requesting golemio api.
	code copied from https://golemioapi.docs.apiary.io/#reference/public-transport/vehicle-positions/get-all-vehicle-positions
	access token generated by https://api.golemio.cz/api-keys/auth/sign-in
"""
headers = {
	'Content-Type': 'application/json; charset=utf-8',
	'x-access-token': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNpem1hcmZpbGlwQGdtYWlsLmNvbSIsImlkIjo3NiwibmFtZSI6bnVsbCwic3VybmFtZSI6bnVsbCwiaWF0IjoxNTcwNTQ2MTU2LCJleHAiOjExNTcwNTQ2MTU2LCJpc3MiOiJnb2xlbWlvIiwianRpIjoiMzAxYWNhNDUtNGRlNC00ZDRmLWI4NzAtMzQwMDQ5OTM1MzBhIn0.4rCELzCNY8XOSvjqQA7cKocPGJ8D2ezhXiWUkIRUNjg'
}

if __name__ == "__main__":
	parser = argparse.ArgumentParser()
	parser.add_argument("--file_name", default="last_positions", type=str, help="The last generated output file")
	parser.add_argument("--update_time", default=20, type=int, help="Time to next request")
	parser.add_argument("--update_error", default=20, type=int, help="Update time if network error occurred")
	parser.add_argument("--log", default="veh_pos_proc.log", type=str, help="Name of logging file")
	parser.add_argument("--trips_folder", default="../data/trips", type=str, help="Name of trips folder")
	args = parser.parse_args()
	logging.basicConfig(format='%(asctime)s %(levelname)s: %(message)s', level=logging.INFO, filename=args.log, filemode='w')
	logging.info("Program has started")

	active_trips = {key[:-6]: deque() for key in os.listdir(args.trips_folder)}
	active_trips_set = {key[:-6] for key in os.listdir(args.trips_folder)}


	# uncomment the following code for empty trips.shape folder after relaunch (deprecated)
	# active_trips = set()
	# shutil.rmtree(args.trips_folder)
	# os.makedirs(args.trips_folder)

	while True:

		"""
			Download the actual information about buses 
			and store them in the json_data array.
		"""

		req_start = time.time()
		try:
			json_vehiclepositions = downloadURL(Request('https://api.golemio.cz/v1/vehiclepositions', headers=headers))
		except URLError as e:
			logging.error("Network error: " + str(e))
			time.sleep(args.update_error - (time.time() - req_start))
			continue

		"""
			Process json data and generate geojson file
		"""
		geojson_vehiclepositions = {}
		geojson_vehiclepositions["type"] = "FeatureCollection"
		geojson_vehiclepositions["timestamp"] = time.strftime("%Y-%m-%d-%H:%M:%S")
		geojson_vehiclepositions["features"] = []

		current_trips_set = set()

		for bus_input_list in json_vehiclepositions["features"]:
			bus_properties = bus_input_list["properties"]["trip"]
			current_trip_gtfs_id = bus_properties["gtfs_trip_id"]
			bus_output_list = {}
			bus_output_list["type"] = "Feature"
			bus_output_list["properties"] = {}
			bus_output_list["properties"]["gtfs_trip_id"] = current_trip_gtfs_id
			bus_output_list["properties"]["gtfs_route_short_name"] = bus_properties["gtfs_route_short_name"]
			bus_output_list["geometry"] = {}
			bus_output_list["geometry"]["coordinates"] = bus_input_list["geometry"]["coordinates"]
			bus_output_list["geometry"]["type"] = "Point"
			geojson_vehiclepositions["features"].append(bus_output_list)

			current_trips_set.add(current_trip_gtfs_id)

			"""
				v promene se drzi polohy busu za poslednich 10 minut
			"""
			if current_trip_gtfs_id not in active_trips or len(active_trips[current_trip_gtfs_id]) == 0:
				active_trips[current_trip_gtfs_id] = deque()
				active_trips[current_trip_gtfs_id].append([bus_input_list["geometry"]["coordinates"], bus_input_list["properties"]["last_position"]["origin_time"], bus_input_list["properties"]["last_position"]["gtfs_shape_dist_traveled"]])
			else:
				active_trips[current_trip_gtfs_id].append([bus_input_list["geometry"]["coordinates"], bus_input_list["properties"]["last_position"]["origin_time"], bus_input_list["properties"]["last_position"]["gtfs_shape_dist_traveled"]])
				while len(active_trips[current_trip_gtfs_id]) > 0 and is_old(active_trips[current_trip_gtfs_id][0]):
					active_trips[current_trip_gtfs_id].popleft()

			logging.info("Trip " + current_trip_gtfs_id + " positions file updated")

		with open(args.file_name, "w+") as f:
			f.seek(0)
			f.write(json.dumps(geojson_vehiclepositions))
			f.close()
			logging.info("Vehicle positions file updated")

		for trip in active_trips_set - current_trips_set:
			active_trips.pop(trip)
			try:
				os.remove(Path(args.trips_folder) / (trip + ".shape"))
				os.remove(Path(args.trips_folder) / (trip + ".lfms"))
				logging.info("Shape of trip " + trip + " file removed")
			except FileNotFoundError as e:
				logging.warning("Some file for trip " + trip + "not found. " + str(e))

		for trip in current_trips_set - active_trips_set:
			try:
				json_data_trip = downloadURL(Request('https://api.golemio.cz/v1/gtfs/trips/' + trip + '?includeShapes=true', headers=headers))
				geojson_shape = transform_shape_json_file(json_data_trip)

				with open(Path(args.trips_folder) / (trip + ".shape"), "w+") as f:
					f.seek(0)
					f.write(json.dumps(geojson_shape))
					f.close()
					logging.info("New shape of trip " + trip + " file exported")
			except URLError as e:
				logging.error("Network error: " + str(e))
				current_trips_set -= trip
				continue

		active_trips_set = current_trips_set

		for trip in current_trips_set:
			json_data_trip = downloadURL(Request('https://api.golemio.cz/v1/gtfs/trips/' + trip + '?includeShapes=true', headers=headers))
			geojson_lfms = {}
			geojson_lfms["type"] = "FeatureCollection"
			geojson_lfms["features"] = [{}]
			geojson_lfms["features"][0]["type"] = "Feature"
			geojson_lfms["features"][0]["properties"] = {}
			geojson_lfms["features"][0]["geometry"] = {}
			geojson_lfms["features"][0]["geometry"]["type"] = "LineString"
			geojson_lfms["features"][0]["geometry"]["coordinates"] = []

			geojson_lfms["features"][0]["geometry"]["coordinates"].append(active_trips[trip][0][0])

			for shape_fault in json_data_trip["shapes"]:
				if float(shape_fault["properties"]["shape_dist_traveled"]) > float(active_trips[trip][0][2]) and float(shape_fault["properties"]["shape_dist_traveled"]) < float(active_trips[trip][len(active_trips[trip]) - 1][2]):
					geojson_lfms["features"][0]["geometry"]["coordinates"].append(shape_fault["geometry"]["coordinates"])

			geojson_lfms["features"][0]["geometry"]["coordinates"].append(active_trips[trip][len(active_trips[trip]) - 1][0])
			with open(Path(args.trips_folder) / (trip + '.lfms'), "w+") as f:
				f.seek(0)
				f.write(json.dumps(geojson_lfms))
				f.close()

		try:
			time.sleep(args.update_time - (time.time() - req_start))
		except Exception as e:
			logging.warning("Sleep failed, " + str(e))
			continue
